### ISSUE TITLE
bidirectional edge

### ISSUE THREAD

**Issue by neel** [saeschdivara/ArangoPy#15]
In arangodb there is no option to create bidirectional edge. However two directed edges can be created. When using `CollectionModel` and `ForeignKeyField` we specify one column (`_from` or `_to`) to be foreign key to another single table only. So there is no way to create a bidirectional edge.

**Comment by neel** [comment]
I am very new to graph database. And I have started with Arango. I don't know what are the queries that I will encounter in future. So I don't want to create bottlenecks. So I wanted to created undirected or bidirectional edges everywhere. However as only directed edges are supported my current understanding is If some vertex is not reachable by a directed traversal then I will hit a bottleneck latter. Please correct me if I am wrong. Because for this reason I am planning to create a counter edge whenever I create an edge. 

I was not aware of the `other_side` parameter. Does that create a counter edge in another table ? or thats and ORM only construct ?

**Comment by saeschdivara** [comment]
I am not sure anymore because I haven't worked with the framework for quite some time but as far as I understand it, unless you set the class attribute collection_type to 3 (Edge collection) only document collections are created. So foreign key as far as I know won't create extra collections. Please take a look at the code of the ManyToManyField which in turn creates an edge collection to connect them (see https://github.com/saeschdivara/ArangoPy/blob/master/arangodb/orm/fields.py#L914 and https://github.com/saeschdivara/ArangoPy/blob/master/arangodb/orm/fields.py#L942). This might be more what you want

**Comment by neel** [comment]
Hm. I'll check that. But is my understanding about bidirectional edge correct ? Otherwise I'll reconsider my design.

**Comment by saeschdivara** [comment]
I don't know about your design. This you should probably check on stackoverflow or with somebody from ArangoDB

**Comment by saeschdivara** [comment]
I will close this issue. If there is something, reopen it
